particle: "Bs"

inputs:
  data: "/home/fcatalan/Desktop/Analyses/Bs_Run3/local_workflow_output/LHC23_pass4_LHC24_pass1_merged/linear_sel/AO2D_merged.root:DF_2298103932356800/O2hfredcandbslite"
  mc: "/home/fcatalan/Desktop/Analyses/Bs_Run3/local_workflow_output/LHC24i_3_4_merged/linear_sel/AO2D_merged.root:DF_2298103923608000/O2hfredcandbslite"

cutset_file_name: '../config/cutset.yaml'

fit_configs:
  pt_int:
    activate: true
    signal_funcs: ["gaussian"]
    bkg_funcs: ["expo"]
    mass_limits: [5.00, 5.75]
    use_bkg_templ: true
  # below one per pT bin
  signal_funcs: [["gaussian"]]
  bkg_funcs: [["expo"]]
  mass_limits: [[5.00, 5.75]]
  use_bkg_templ: [true]

plot_style:
  pt_int:
    n_bins: 75
  n_bins: [75]

outputs:
  directory: "/home/fcatalan/Desktop/Analyses/Bs_Run3/local_workflow_output/LHC23_pass4_LHC24_pass1_merged/linear_sel/fit_pt2_100"
  suffix: ""

