particle: 'Bs'

reco_file_names: '~/Desktop/Analyses/Bs_Run3/local_workflow_output/LHC23c1_train308487/linear_sel/AO2D_merged.root:DF_2835056186000/O2hfredcandbslite'

gen:
  file_names: ['~/Desktop/Analyses/Bs_Run3/local_workflow_output/LHC23c1_train308487/trigger_sel/AnalysisResults.root']
  sparse_name: 'hf-task-bs-reduced/hPtYGenSig'
  sparse_name_acc: 'hf-task-bs-reduced/hPtYWithProngsInAccepanceGenSig'
  pt_axis: 0

reco:
  sparse_name: 'hf-task-bs-reduced/hMassPtCutVarsRecSig'
  pt_axis: 1

cutset_file_name: 'config/cutset.yaml'

output_file_name: '~/Desktop/Analyses/Bs_Run3/local_workflow_output/LHC23c1_train308487/linear_sel/efficiency.root'
